/* MANUAL ARTICLE DETAILS — English
   Edit the paragraph strings below. Keep the array order aligned with the place IDs. */
window.SIRASA_ARTICLE_DETAILS = window.SIRASA_ARTICLE_DETAILS || {};
window.SIRASA_ARTICLE_DETAILS.en = [
  [
    "Sagama Rajamaha Viharaya is located in Bootawatta village in the Pathahewaheta Divisional Secretariat Division of Kandy District. To reach the temple, travel from Kandy towards Thalathuoya and then proceed approximately 14 km along the Bawlana Road. This is also the first location mentioned in the Buddhist historical text known as the “Nam Potha.”Historical records state that the construction of Sagam Rajamaha Viharaya began during the reign of King Devanampiya Tissa and was further developed during the Gampola Kingdom period.",
    "The temple also features an image house adorned with Kandyan-era paintings and sculptures, as well as a stone enclosure built around the ancient Bodhi tree and a two-storied building. The image house, bell-shaped stupa, Uposatha house, and old residential quarters are among the archaeologically significant structures found at the temple.",
    "According to legend, during the Anuradhapura period, a sapling of the sacred Jaya Sri Maha Bodhi was being taken to Ruhuna. It is believed that the sapling took root at the place where it was temporarily kept. An inscription on a rock near Sagama Temple records that, during the reign of King Bhuvanekabahu V, two ministerial brothers, Alakeshvara and Deva Mantri, donated forty amunas of paddy land in Haputhale village to Senkadagala Natha Deity and Rukwasi Deity. The Aluth Sahal Mangallaya (New Rice Festival) is also held at the Sagama Rajamaha Viharaya, using rice collected from the six villages of Godamunna, Bootawatta, Nugaliyadda, Kapuliyadda, Haputhale, and Mahamadagama."
  ],
  [
    "This historic temple is located in the Seruwila Grama Niladhari division, within the Seruwila Divisional Secretariat area of the Trincomalee District in the Eastern Province. An inscription engraved on a rock, dating back to the reign of King Kassapa IV (AD 839–914), can be seen near the steps of the western entrance of the stupa. In this inscription, the temple is referred to as “Tissa Maha Vihara” or “Tis Maha Vehera.”According to both the Pali Dhathuwanshaya and the Sinhala Dhathuwanshaya, this is the historic Tissa Maha Vihara built near Seruwila, south of the Mahaweli River, enshrining the sacred forehead relic of the Buddha. Archaeological evidence has confirmed that this temple is indeed the same ancient Tissa Maha Vihara mentioned in these texts.",
    "The Dathavamsa states that this great stupa enshrines not only the sacred forehead relic (Lalata Dhathu) of the Buddha, but also a portion of the hair relics that were given by the Buddha, during his lifetime, to the merchant brothers Tapassu and Bhalluka. It is also mentioned that the stupa was constructed during the reign of King Kavantissa (209–164 BC).",
    "This temple is a monastery built in accordance with the Maha Vihara tradition, with the stupa as its central feature. Within this historic sacred site, several archaeological remains can be identified, including the stupa, Bodhigharaya, Prathimagharaya, Uposathagharaya, Pradhanagaraya, ponds, ruins of a building constructed on stone pillars, stone caves, Waraha Sondi Gal Kemiya, stone inscriptions, and other monastic complex structures.",
    "This stupa, which had fallen into ruins due to various reasons, was restored in the 1920s under the leadership of the Seruwila Mangala Maha Chaitya Development Society. On 02.11.1962, the Department of Archaeology officially declared the area as a protected site and preserved it for future generations."
  ],
  [
    "he sacred site of the Sri Sankhapala Raja Maha Viharaya is located in the Sankhapala Grama Niladhari Division of the Embilipitiya Divisional Secretariat Division in the Ratnapura District of the Sabaragamuwa Province. The origin of the temple and its Nindagama are evidenced to belong to the reign of King Dutugemunu. Warrior Phussadeva can be pointed out as one of the ten great warriors who commanded Prince Gemunu's army during the war against King Elara. After winning the war with King Elara, King Dutugemunu granted the village of Pallebedda to the Warrior Phussadeva as a land grant (Gamwaraya). Sources reveal that it was 12,600 acres. He had accepted the land grant (Nindagama) and arrived there with his relatives to live in this village. Later, he carved stones in the cave (Kataram) in Nindagama and offered it to the monks. The name Pussadeva is also mentioned in the pre-Brahminic cave inscriptions at the Sankhapala Rajamaha Viharaya.",
    "‘‘......... Putha Pusha Dewasha Lene Shagasa”",
    "‘‘ Pusha Dewasha Putha ......... Guthasha Dane Lene “",
    "The information given in these articles confirms that the Sankhapala Temple was a temple that initiated and developed during the pre-Christian era. There is also a carving of a conch on the top of one of the caves here. There are literary evidences that this temple was renovated during the reigns of King Maha Parakramabahu and Nissankamalla during the Polonnaruwa period after the Anuradhapura period. Later, much information about this temple, which remained hidden from history for a while, was discovered during the Kandyan era. It is a story related to the Rev. Karathota Dhammarama Thero during the reign of King Rajadhi Rajasinghe. He had composed a wonderful poem called ‘‘Barasa Kavya’’ (Bara Nama Kava Saka, Garbha Nama Chakraya) extolling the virtues of the Lord Buddha, which can be seen today in front of the gate of the old temple. The village of Pallebedda, which was presented to the Warrior Phussadeva by King Dutugemunu, was again offered to the Rev. Karathota Dhammarama Thero by King Rajadhi Rajasinghe in 1786 AD.",
    "The vicinity of this temple has been systematically explored by the Department of Archaeology in the years 1985, 2007, and 2024. Numerous sites with cave inscriptions in the pre-Brahmi script, caves without inscriptions carved in the cave, natural caves, Dagoba mounds, remains of rocky buildings, moon stones, and stone pillars have been identified in this temple and in the Nindagama belonging to the temple. The Pussadeva Tomb (Saya), the nearby carved cave, and the fifteen ancient Sankhapala cave temples with and without stones carved Brahmi scripts were declared as archaeologically protected monuments by Gazette No. 1264 dated 22.11.2002. Similarly, a 200-yard protective zone has been imposed around the ruins of Pussadeva Tomb of the Sankapala Vihara and the cave situated at the vicinity by Gazette No. 1344 dated 04.06.2004, and a 400-yard protective zone has been imposed by Gazette No. 1394 dated 20.05.2005."
  ],
  [
    "King Kirthi Sri Nissankamalla, who reigned from 1187 to 1196 AD, was a great leader who explored the whole island during his reign. While traveling from Pulathisipura to Devinuwara in the southern province, the king entered the city of Raigam and performed a special alms giving called \"Thuladhara Danaya\", which he often offered at this sacred place. Later, according to his order, a stone statue was placed on a stone base on this land and the Maha Devalaya — the Upulvan Sri Vishnu Maha Devalaya — was built.",
    "Since the main road network leading to the four corners of Sri Lanka runs through the vicinity of this historic temple, the historical and ancient Bo Tree, which has been worshiped and sought blessings by those who pass through this sacred place even before the construction of the temple — by lighting lamps and making offerings — still stands and flourishes in this place today.",
    "This Maha Devalaya, renowned during the Gampola and Kotte eras, was renovated by the royal family including the heroic Minister Alakeshwara of the Alagakkonara dynasty. After placing a stone statue of Vishnu, it became famous as the Raigampura Maha Viharaya.— Historical Chronicles of Sri Lanka",
    "This temple, built with the support of various royal families and Sri Lankan noble families for centuries, is a sacred place where people from all over Sri Lanka visit to pray for blessings. After the Kotte era renovations and the enshrinement of the Vishnu statue, it was known as Raigampura Maha Viharaya — the Great Temple of Raigam.",
    "During the reign of Keerthi Sri Rajasinghe from 1747 to 1782 AD, the sacred site of the historic Maha Devala was developed as a Buddhist monastery with the arrival of Venerable Ginigathpitiye Sri Sangharakkhita — who was titled chief Sanghanayake of the Satkorala Maha Disawa — along with Venerable Kuda Ginigathpitiye Sri Deepankara Thero and Venerable Dope Sri Gunarathana Anu Nayaka Thero, who were among the chief disciples of the Great Venerable Sangharaja Maha Thero."
  ],
  [
    "ambadeniya Viharaya (Dambadeniya Sri Vijayasundararama Raja Maha Viharaya). Dambadeniya Sri Vijayasundararama Raja Maha Viharaya is located in Dambadeniya South Grama Niladhari Division in the Narammala Divisional Secretariat Division of the Kurunegala District in the North Western Province.",
    "The Mahavamsa affirms that among the regional rulers who organized themselves by establishing regional administrative centers in various areas with the collapse of the Polonnaruwa Kingdom, King Vijayabahu III established his administrative hub centering Malingagala, Dambadeniya.",
    "Construction of the Dambadeniya Sri Wijesundararama Viharaya is a significant mission executed by King Vijayabahu III (1232 AD – 1236 AD). The Mahavamsa and Poojavali reveal that the sacred Tooth Relic and the sacred Bowl Relic were hidden in the Kotmale area during the reign of Kalinga Magha, and were brought back to Dambadeniya by King Vijayabahu III and placed in Beligala for greater safety.",
    "A Buddhist religious revival took place centering Dambadeniya Sri Vijayasundararamaya during the reign of King Parakramabahu II (1236 AD - 1270 AD), a prominent ruler of the Dambadeniya Kingdom. Sources reveal that the Temple of the Sacred Tooth Relic was blazed and destroyed during foreign invasions and that later, during the Kandyan period, the three-story Temple of the Sacred Tooth Relic was renovated and turned it into a two-story palace, and new paintings were painted by Meegasthenna Adhikaram over the old paintings by plastering them over. According to an excavation conducted at the site by the Department of Archaeology, evidence of wall paintings has been identified during three occasions. When considering as a whole, the paintings and sculptures in the image house reflect the features of traditional stylized painting of the Kandyan period as well as the features of post-Kandyan painting and sculpture.",
    "Verses 31, Chapter 81, Mahavamsa · Pages 109–110, Poojavaliya"
  ]
];
